# Generated by Django 4.2.7 on 2025-10-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter phone number in +91XXXXXXXXXX format', max_length=15),
        ),
    ]
