# Generated by Django 4.2.7 on 2025-10-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='availability',
            field=models.BooleanField(default=True, help_text='Available for task assignment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('manager', 'Manager'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
