# Generated by Django 4.2.7 on 2025-10-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_status_taskassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
        migrations.DeleteModel(
            name='TaskAssignment',
        ),
    ]
